API_key_1: "AIzaSyA312cLkHj8n2KuAZqhYwBkXJQ360VfoAk"

email_id: "khurramrashid.novatore@gmail.com"
email_password: "Nokia.5130"
username: "khurramrashid"
address: "smtp.sendgrid.net"
domain: "gmail.com"
